# Generated by Django 4.2.7 on 2023-11-03 07:24

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Sns",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("SNSemail", models.CharField(max_length=50)),
                ("SNSpassword", models.CharField(max_length=50)),
            ],
        ),
    ]
