# Generated by Django 4.2.7 on 2023-11-03 06:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sns", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sns",
            name="SNSemail",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="sns",
            name="SNSpassword",
            field=models.CharField(max_length=50),
        ),
    ]
